var constants;

constants = {
  RECEIVE_LOGIN_USER: 'RECEIVE_LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_POST: 'RECEIVE_POST',
  DELETE_POST: 'DELETE_POST',
  PUT_POST: 'PUT_POST',
  RECEIVE_EVENT: 'RECEIVE_EVENT'
};

module.exports = constants;
