var constants;

constants = {
  RECEIVE_LOGIN_USER: 'RECEIVE_LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_POST: 'RECEIVE_POST',
  DELETE_POST: 'DELETE_POST',
  PUT_POST: 'PUT_POST',
  UPDATE_VIEWER_COUNT: 'UPDATE_VIEWER_COUNT',
  RECEIVE_EVENT: 'RECEIVE_EVENT',
  RECEIVE_COMMENT: 'RECEIVE_COMMENT'
};

module.exports = constants;
